version: "3"
services:
  node1:
    build: ./website
    ports:
      - 8080
  node2:
    build: ./website
    ports:
      - 8080
  node3:
    build: ./website
    ports:
      - 8080
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - node1:node1
      - node2:node2
      - node3:node3